const productsData = `[
    {
        "image": "./image/product-img-1.jpg",
        "alt": "A male model in a dark-blue bomber jacket carrying a light-grey backpack",
        "width": 360,
        "height": 420,
        "productTitle": "Ellery x m'o capsule",
        "type": "Jacket",
        "color": "blue",
        "size": "Xl",
        "details": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "52.00",
        "quantity": "1",
        "id": "1"
    },
    {
        "image": "./image/product-img-2.jpg",
        "alt":"A female model in a black suit and stilettos",
        "width": 360,
        "height": 420,
        "productTitle": "Ellery x m'o capsule",
        "type": "Women's Suit",
        "color": "black",
        "size": "S",
        "details": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "52.00",
        "quantity": "1",
        "id": "2"
    },
    {
        "image": "./image/product-img-3.jpg",
        "alt": "A male model in a dark-blue and black hoodie and ivory shorts",
        "width": 360,
        "height": 420,
        "productTitle": "Ellery x m'o capsule",
        "type": "T-Shirt",
        "color": "dark-blue",
        "size": "M",
        "details": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "52.00",
        "quantity": "1", 
        "id": "3" 
    },
    {
        "image": "./image/product-img-4.jpg",
        "alt": "A male model in a blue t-shirt and yellow trousers",
        "width": 360,
        "height": 420,
        "productTitle": "Ellery x m'o capsule",
        "type": "Trousers",
        "color": "yellow",
        "size": "XXL",
        "details": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "52.00",
        "quantity": "1",
        "id": "4" 
    },
    {
        "image": "./image/product-img-5.jpg",
        "alt":"A female model in a light blue jacket",
        "width": 360,
        "height": 420,
        "productTitle": "Ellery x m'o capsule",
        "type": "Jacket",
        "color": "light blue",
        "size": "XXS",
        "details": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "52.00",
        "quantity": "1",
        "id": "5" 
    },
    {
        "image": "./image/product-img-6.jpg",
        "alt": "A female model in white-striped blouse",
        "width": 360,
        "height": 420,
        "productTitle": "Ellery x m'o capsule",
        "type": "Blouse",
        "color": "olive",
        "size": "L",
        "details": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "52.00",
        "quantity": "1",
        "id": "6"
    }
]`